default: &default
  submissions:
    recommended:
      max_results: 100
      default_results: 8
    by_subreddit:
      max_results: 100
      default_results: 40
    related:
      max_results: 100
      default_results: 8

  subreddits:
    index:
      max_results: 100
      default_results: 50
    recommended:
      max_results: 100
      default_results: 5
    popular:
      max_results: 100
      default_results: 5

  favorite_submissions:
    index:
      max_results: 100
      default_results: 50


production:
  <<: *default

development:
  <<: *default

test:
  submissions:
    recommended:
      max_results: 10
      default_results: 5
    by_subreddit:
      max_results: 10
      default_results: 5
    related:
      max_results: 10
      default_results: 5

  subreddits:
    index:
      max_results: 25
      default_results: 5
    recommended:
      max_results: 25
      default_results: 5
    popular:
      max_results: 25
      default_results: 5

  favorite_submissions:
    index:
      max_results: 25
      default_results: 5