secret_key_base: #your secret key

production:
  mailer:
    sender: # your mailer sender (e.g. Project Free <my@email.com>)
    address: # your mailer address (e.g. smtp.gmail.com)
    user_name: # your mailer user name (e.g. mymailer@gmail.com)
    password: # your mailer password
    domain: # domain for the app
    port: # mailer port

  reddit:
    user_agent: # choose a user_agent that will be send with requests to reddit
    client_id: # reddit api client_id
    secret: # reddit api secret

  storage:
    key: # storage key for digital ocean spaces
    secret: # secret for digital ocean spaces
    bucket: # bucket for digital ocean spaces
    region: # region for digital ocean spaces
    endpoint: # endpoint for digital ocean spaces

development:
  mailer:
    sender: # mailer sender for development

  reddit:
    user_agent: # choose a user_agent that will be send with requests to reddit
    client_id: # reddit api client_id
    secret: # reddit api secret

test:
  mailer:
    sender: # mailer sender for test

  reddit:
    user_agent: # choose a user_agent that will be send with requests to reddit
    client_id: # reddit api client_id
    secret: # reddit api secret
